### ISSUE TITLE
Problem with first_name | driver for facebook

### ISSUE THREAD

**Issue by AbdumanonNurov** [fondbot/drivers-facebook#3]
FondBot.ERROR: Whoops\Exception\ErrorException: Undefined index: first_name

Full:

> FondBot.ERROR: Whoops\Exception\ErrorException: Undefined index: first_name in /var/www/bot.funny-spanish.com/vendor/fondbot/facebook/src/FacebookDriver.php:114 Stack trace: #0 /var/www/bot.funny-spanish.com/vendor/fondbot/facebook/src/FacebookDriver.php(114): Whoops\Run->handleError(8, 'Undefined index...', '/var/www/bot.fu...', 114, Array) #1 /var/www/bot.funny-spanish.com/vendor/fondbot/framework/src/Conversation/SessionManager.php(38): FondBot\Drivers\Facebook\FacebookDriver->getUser() #2 /var/www/bot.funny-spanish.com/vendor/fondbot/framework/src/Application/Kernel.php(109): FondBot\Conversation\SessionManager->load(Object(FondBot\Channels\Channel), Object(FondBot\Drivers\Facebook\FacebookDriver)) #3 /var/www/bot.funny-spanish.com/vendor/fondbot/framework/src/Conversation/ConversationManager.php(54): FondBot\Application\Kernel->loadSession(Object(FondBot\Channels\Channel), Object(FondBot\Drivers\Facebook\FacebookDriver)) #4 /var/www/bot.funny-spanish.com/vendor/fondbot/framework/src/Application/Controller.php(26): FondBot\Conversation\ConversationManager->handle('facebook', Object(FondBot\Http\Request)) #5 [internal function]: FondBot\Application\Controller->webhook(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Array) #6 /var/www/bot.funny-spanish.com/vendor/league/route/src/Strategy/ApplicationStrategy.php(22): call_user_func_array(Array, Array) #7 /var/www/bot.funny-spanish.com/vendor/league/route/src/Middleware/ExecutionChain.php(41): League\Route\Strategy\ApplicationStrategy->League\Route\Strategy\{closure}(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Closure)) #8 /var/www/bot.funny-spanish.com/vendor/league/route/src/Middleware/ExecutionChain.php(23): League\Route\Middleware\ExecutionChain->League\Route\Middleware\{closure}(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response)) #9 /var/www/bot.funny-spanish.com/vendor/league/route/src/RouteCollection.php(130): League\Route\Middleware\ExecutionChain->execute(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response)) #10 /var/www/bot.funny-spanish.com/public/index.php(13): League\Route\RouteCollection->dispatch(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response)) #11 {main} [] []

**Comment by golubkovden** [comment]
Hello @AbdumanonNurov.
Could you say which client for message did you used (web, facebook mobile app, messenger app)?
Print the version of packages. `composer show -i | grep fondbot`

**Comment by AbdumanonNurov** [comment]
Hi,
I'm used web version facebook messenger 

**composer show -i | grep fondbot**

fondbot/facebook                    v1.0.0  Facebook Messenger driver for FondBot
fondbot/framework                   v1.0.5  FondBot framework.

**Comment by golubkovden** [comment]
Hmm, just tested and everything is fine, for me.
Could you print what `$user` is contains. 
p.s. for more productivity we can discuss in slack.

**Comment by vladimir-yuldashev** [comment]
Fixed in v1.0.1
