### ISSUE TITLE
FondBot.ERROR:  FB Driver | GuzzleHttp\Exception\ClientException | No matching user found

### ISSUE THREAD

**Issue by AbdumanonNurov** [fondbot/drivers-facebook#4]
I used fb driver version v1.0.1

> [2017-06-25 23:54:15] FondBot.ERROR: GuzzleHttp\Exception\ClientException: Client error: `POST https://graph.facebook.com/v2.6/me/messages?access_token=<скрыл токен>` resulted in a `400 Bad Request` response: {"error":{"message":"(#100) No matching user found","type":"OAuthException","code":100,"error_subcode":2018001,"fbtrace_ (truncated...)  in /var/www/bot.funny-spanish.com/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:111 Stack trace: #0 /var/www/bot.funny-spanish.com/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 /var/www/bot.funny-spanish.com/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 /var/www/bot.funny-spanish.com/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array) #3 /var/www/bot.funny-spanish.com/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() #4 /var/www/bot.funny-spanish.com/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promise\TaskQueue->run(true) #5 /var/www/bot.funny-spanish.com/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn() #6 /var/www/bot.funny-spanish.com/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending() #7 /var/www/bot.funny-spanish.com/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList() #8 /var/www/bot.funny-spanish.com/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending() #9 /var/www/bot.funny-spanish.com/vendor/guzzlehttp/guzzle/src/Client.php(129): GuzzleHttp\Promise\Promise->wait() #10 /var/www/bot.funny-spanish.com/vendor/guzzlehttp/guzzle/src/Client.php(87): GuzzleHttp\Client->request('post', 'https://graph.f...', Array) #11 /var/www/bot.funny-spanish.com/vendor/fondbot/facebook/src/FacebookCommandHandler.php(41): GuzzleHttp\Client->__call('post', Array) #12 /var/www/bot.funny-spanish.com/vendor/fondbot/framework/src/Drivers/CommandHandler.php(55): FondBot\Drivers\Facebook\FacebookCommandHandler->handleSendMessage(Object(FondBot\Drivers\Commands\SendMessage)) #13 /var/www/bot.funny-spanish.com/vendor/fondbot/framework/src/Drivers/Driver.php(114): FondBot\Drivers\CommandHandler->handle(Object(FondBot\Drivers\Commands\SendMessage)) #14 /var/www/bot.funny-spanish.com/vendor/fondbot/framework/src/Queue/Adapters/SyncAdapter.php(34): FondBot\Drivers\Driver->handle(Object(FondBot\Drivers\Commands\SendMessage)) #15 /var/www/bot.funny-spanish.com/vendor/fondbot/framework/src/Conversation/Traits/SendsMessages.php(35): FondBot\Queue\Adapters\SyncAdapter->push(Object(FondBot\Channels\Channel), Object(FondBot\Drivers\Facebook\FacebookDriver), Object(FondBot\Drivers\Commands\SendMessage)) #16 /var/www/bot.funny-spanish.com/vendor/fondbot/framework/src/Conversation/FallbackIntent.php(30): FondBot\Conversation\Intent->sendMessage('My developer di...') #17 /var/www/bot.funny-spanish.com/vendor/fondbot/framework/src/Conversation/Intent.php(40): FondBot\Conversation\FallbackIntent->run(Object(FondBot\Drivers\Facebook\FacebookReceivedMessage)) #18 /var/www/bot.funny-spanish.com/vendor/fondbot/framework/src/Conversation/ConversationManager.php(95): FondBot\Conversation\Intent->handle(Object(FondBot\Application\Kernel)) #19 /var/www/bot.funny-spanish.com/vendor/fondbot/framework/src/Conversation/ConversationManager.php(58): FondBot\Conversation\ConversationManager->converse(Object(FondBot\Conversation\FallbackIntent)) #20 /var/www/bot.funny-spanish.com/vendor/fondbot/framework/src/Application/Controller.php(26): FondBot\Conversation\ConversationManager->handle('facebook', Object(FondBot\Http\Request)) #21 [internal function]: FondBot\Application\Controller->webhook(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Array) #22 /var/www/bot.funny-spanish.com/vendor/league/route/src/Strategy/ApplicationStrategy.php(22): call_user_func_array(Array, Array) #23 /var/www/bot.funny-spanish.com/vendor/league/route/src/Middleware/ExecutionChain.php(41): League\Route\Strategy\ApplicationStrategy->League\Route\Strategy\{closure}(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Closure)) #24 /var/www/bot.funny-spanish.com/vendor/league/route/src/Middleware/ExecutionChain.php(23): League\Route\Middleware\ExecutionChain->League\Route\Middleware\{closure}(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response)) #25 /var/www/bot.funny-spanish.com/vendor/league/route/src/RouteCollection.php(130): League\Route\Middleware\ExecutionChain->execute(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response)) #26 /var/www/bot.funny-spanish.com/public/index.php(13): League\Route\RouteCollection->dispatch(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response)) #27 {main} [] []

**Comment by golubkovden** [comment]
Hi @AbdumanonNurov.
Looks like you somehow wrote bot message from facebook page. We're currently supporting only user-to-bot conversation.  

> This request, as per the documentation, requires a user id, however <id> seems to refer to a page. (from facebook support)

**Comment by golubkovden** [comment]
Resolved by subscribing on only messages event.
